# This file is the Jenkins entry point. The Jenkins job should be
# configured to run:
#
#     make -f Makefile.jenkins

all: gondar-linux gondar-win32

gondar-linux:
	sudo docker build -f docker/gondar-linux.Dockerfile .

gondar-win32:
ifdef RELEASE
	python package.py --release
else
	python package.py
endif

.PHONY: \
	all \
	gondar-linux \
	gondar-win32
